export const FETCH_FOOTBALL_EVENTS = 'FETCH_FOOTBALL_EVENTS';
export const FINISHED_FETCHING_EVENTS = 'FINISHED_FETCHING_EVENTS';
export const ERROR_FETCHING_EVENTS = 'ERROR_FETCHING_EVENTS';
export const SELECT_EVENT = 'SELECT_EVENT';